<#
.SYNOPSIS
  Prepare or refresh a clean release branch for public / NuGet publication.

.DESCRIPTION
  Creates or checks out release/<Version> from an annotated tag (default v3.0.0),
  and optionally builds a filtered public mirror directory without harness/ or external/.

  Development monorepo (phase-8/feature-parity) keeps harness and submodules.
  Public remotes should receive only the mirror output or the documented path subset.

.PARAMETER Version
  Release version without 'v' prefix (e.g. 3.0.0).

.PARAMETER Tag
  Annotated tag name. Defaults to "v<Version>".

.PARAMETER Mirror
  Clone release branch and copy only publishable paths to -OutputDir (no git filter-repo required).

.PARAMETER OutputDir
  Target directory for -Mirror (default: sibling ../xuguefcore-public).

.PARAMETER Force
  Recreate -OutputDir if it exists (mirror only).

.EXAMPLE
  harness/scripts/prepare-release-branch.ps1
  # Checkout release/3.0.0 from v3.0.0

.EXAMPLE
  harness/scripts/prepare-release-branch.ps1 -Mirror -OutputDir E:\publish\xuguefcore-public
  # Produce minimal public tree for git init + push
#>
param(
    [string]$Version = "3.0.0",
    [string]$Tag = "",
    [switch]$Mirror,
    [string]$OutputDir = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
if (-not $Tag) { $Tag = "v$Version" }
$ReleaseBranch = "release/$Version"

$PublishPaths = @(
    ".github",
    "src",
    "test",
    "samples",
    "docs",
    "Directory.Build.props",
    "Directory.Packages.props",
    "NativeAssets.props",
    "NuGet.config",
    "Version.props",
    "global.json",
    "Xugu.EFCore.Xugu.sln",
    ".gitignore",
    "LICENSE",
    "README.md",
    "RELEASE.md"
)

function Test-GitTag([string]$Name) {
    git -C $Root rev-parse --verify "refs/tags/$Name" 2>$null
    return $LASTEXITCODE -eq 0
}

function Test-GitBranch([string]$Name) {
    git -C $Root rev-parse --verify "refs/heads/$Name" 2>$null
    return $LASTEXITCODE -eq 0
}

Write-Host "=== Prepare Release Branch ===" -ForegroundColor Cyan
Write-Host "Root:           $Root"
Write-Host "Tag:            $Tag"
Write-Host "Release branch: $ReleaseBranch"

if (-not (Test-GitTag $Tag)) {
    throw "Tag '$Tag' not found. Create with: git tag -a $Tag -m 'Release $Version'"
}

Push-Location $Root
try {
    if (Test-GitBranch $ReleaseBranch) {
        Write-Host "Checking out existing branch $ReleaseBranch" -ForegroundColor Yellow
        git checkout $ReleaseBranch
        git merge --ff-only $Tag 2>$null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "Branch diverged from $Tag — resolve manually or delete branch and re-run." -ForegroundColor Red
        }
    }
    else {
        Write-Host "Creating $ReleaseBranch from $Tag" -ForegroundColor Green
        git checkout -b $ReleaseBranch $Tag
    }

    if ($Mirror) {
        if (-not $OutputDir) {
            $parent = Split-Path $Root -Parent
            $OutputDir = Join-Path $parent "xuguefcore-public"
        }
        $OutputDir = [System.IO.Path]::GetFullPath($OutputDir)

        if (Test-Path $OutputDir) {
            if (-not $Force) {
                throw "OutputDir exists: $OutputDir. Use -Force to replace contents."
            }
            Remove-Item -Recurse -Force $OutputDir
        }
        New-Item -ItemType Directory -Path $OutputDir | Out-Null

        Write-Host "Building public mirror at $OutputDir" -ForegroundColor Cyan
        foreach ($rel in $PublishPaths) {
            $src = Join-Path $Root $rel
            if (-not (Test-Path $src)) {
                Write-Host "  skip (missing): $rel" -ForegroundColor DarkYellow
                continue
            }
            $dest = Join-Path $OutputDir $rel
            $destParent = Split-Path $dest -Parent
            if (-not (Test-Path $destParent)) {
                New-Item -ItemType Directory -Path $destParent -Force | Out-Null
            }
            if (Test-Path $src -PathType Container) {
                Copy-Item -Path $src -Destination $dest -Recurse -Force
            }
            else {
                Copy-Item -Path $src -Destination $dest -Force
            }
            Write-Host "  copied: $rel"
        }

        # Public README hint file
        $mirrorReadme = @"
# Public mirror

This directory was generated by ``harness/scripts/prepare-release-branch.ps1 -Mirror``.

## Initialize and push

``````powershell
cd "$OutputDir"
git init
git add .
git commit -m "Release $Version GA public mirror"
git branch -M main
git remote add public https://github.com/YOUR_ORG/EntityFrameworkCore.Xugu.git
git push -u public main
git tag $Tag
git push public $Tag
``````

Excluded from mirror: ``harness/``, ``external/``, ``.gitmodules``, ``.gitlab-ci.yml``, ``artifacts/``.

See ``docs/RELEASE-BRANCH-STRATEGY.md`` in the source monorepo.
"@
        Set-Content -Path (Join-Path $OutputDir "MIRROR-README.md") -Value $mirrorReadme -Encoding UTF8

        Write-Host ""
        Write-Host "Mirror ready. Next steps:" -ForegroundColor Green
        Write-Host "  cd `"$OutputDir`""
        Write-Host "  git init && git add . && git commit -m 'Release $Version public mirror'"
        Write-Host "  git remote add public <public-repo-url> && git push -u public main"
    }
    else {
        Write-Host ""
        Write-Host "On branch $ReleaseBranch. Push with:" -ForegroundColor Green
        Write-Host "  git push -u origin $ReleaseBranch"
        Write-Host ""
        Write-Host "For public remote, run with -Mirror to avoid pushing harness/external."
    }
}
finally {
    Pop-Location
}
